name: Notebook-Run

on:
  workflow_dispatch:
    inputs:
      notebookFile:
        description: 'Notebook to run (inside notebook dir)'
        required: true
        default: 'trainer-v4-unit-test/model-init.ipynb'
      gpuTarget:
        description: 'GPU Target (use either 8x12vgb / 1x24vgb)'
        required: true
        default: '1x24vgb'
      cudaVersion:
        description: 'cuda version'
        required: true
        default: '11-8'

env:
  # Notebook runner settings
  gpuTarget: ${{github.event.inputs.gpuTarget}}
  cudaVersion: ${{github.event.inputs.cudaVersion}}
  notebookFile: ${{github.event.inputs.notebookFile}}
  # Secrets
  HUGGING_FACE_HUB_TOKEN: ${{secrets.HUGGING_FACE_HUB_TOKEN}}
  WANDB_API_KEY: ${{secrets.WANDB_API_KEY}}

jobs:
  notebook-run:
    name: ${{github.event.inputs.notebookFile}} on ${{github.event.inputs.gpuTarget}} / cuda-${{github.event.inputs.cudaVersion}}
    runs-on: 
      - cuda-${{github.event.inputs.cudaVersion}}
      - ${{github.event.inputs.gpuTarget}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger the github-runner notebook
        run: |
          cd ./notebook/github-runner
          chmod +x ./github-runner.sh
          ./github-runner.sh ${{github.event.inputs.notebookFile}}
